#include "render_pch.h"
#include "cdll_int.h"
#include "cdll_engine_int.h"
#include "tier2/tier2.h"
#include "tier3/tier3.h"
#include "inputsystem/iinputsystem.h"
#include "vgui_baseui_interface.h"
#include "vgui/IPanel.h"
#include "PortalInputProbe.h"
#include "../../game/shared/in_buttons.h"
#include "SDL.h"
extern IVEngineClient *engineClient;
extern "C" bool SourceIOSDispatchPortalInput();

extern "C" bool SourceIOSCheckPortalClientInput(IOSReadPortalCommand readCommand,IOSFindPortalControl findControl,char *detail,size_t capacity) {
    if (!g_ClientDLL || !readCommand || !findControl) {
        snprintf(detail,capacity,"Portal client input: client/command reader unavailable"); return false;
    }
    bool passed=true;
    vgui::VPANEL ui=EngineVGui()->GetPanel(PANEL_GAMEUIDLL);
    bool visible=g_pVGuiPanel->IsVisible(ui);
    QAngle originalAngles; engineClient->GetViewAngles(originalAngles);
    // This fixture owns no player or level. Temporarily hide the real menu
    // panel to exercise the client's existing gameplay-input gate.
    g_pVGuiPanel->SetVisible(ui,false);
    int sequence=1;
    auto send=[&](Uint32 type,Sint64 finger,float x,float y,float dx=0.f,float dy=0.f) {
        SDL_Event event={}; event.type=type; event.tfinger.touchId=INT64_MAX;
        event.tfinger.fingerId=finger; event.tfinger.x=x; event.tfinger.y=y;
        event.tfinger.dx=dx; event.tfinger.dy=dy;
        passed=(SDL_PushEvent(&event)==1)&&passed;
    };
    auto command=[&]() {
        g_pInputSystem->PollInputState();
        SourceIOSDispatchPortalInput();
        g_ClientDLL->IN_SetSampleTime(1.f/60.f);
        g_ClientDLL->CreateMove(sequence,1.f/60.f,true);
        IOSPortalCommand result={};
        passed=readCommand(sequence++,&result)&&result.serializationMatches&&passed;
        return result;
    };
    auto check=[&](bool condition,const char *label) {
        passed=condition&&passed; Msg("iOS client input %s: %s\n",label,condition?"PASS":"FAIL");
    };
    IOSPortalCommand baseline=command();
    float moveX=0,moveY=0,lookX=0,lookY=0;
    check(findControl("move",&moveX,&moveY) && findControl("look",&lookX,&lookY),"move/look region lookup");
    send(SDL_FINGERDOWN,INT64_MAX,moveX,moveY);
    send(SDL_FINGERDOWN,-999,lookX,lookY);
    command();
    send(SDL_FINGERMOTION,INT64_MAX,moveX-.04f,moveY-.04f,-.04f,-.04f);
    send(SDL_FINGERMOTION,-999,lookX+.04f,lookY+.03f,.04f,.03f);
    IOSPortalCommand moved=command();
    check(moved.forward>0 && moved.side<0 && (moved.buttons&IN_FORWARD),"simultaneous move/look movement");
    check(moved.yaw!=baseline.yaw && moved.pitch!=baseline.pitch,"simultaneous move/look angles");
    IOSPortalCommand stationary=command();
    check(stationary.yaw==moved.yaw && stationary.pitch==moved.pitch,"stationary finger does not rotate camera");
    send(SDL_FINGERUP,INT64_MAX,moveX-.04f,moveY-.04f);
    send(SDL_FINGERUP,-999,lookX+.04f,lookY+.03f);
    IOSPortalCommand released=command();
    check(released.forward==0 && released.side==0,"movement release");
    send(SDL_FINGERDOWN,17,.25f,.4f); command();
    send(SDL_FINGERMOTION,17,.28f,.42f,.03f,.02f);
    IOSPortalCommand leftLook=command();
    check(leftLook.yaw!=released.yaw && leftLook.pitch!=released.pitch,"left screen free-look");
    send(SDL_FINGERUP,17,.28f,.42f); command();
    auto key=[&](SDL_Scancode scancode,bool pressed) {
        SDL_Event event={}; event.type=pressed?SDL_KEYDOWN:SDL_KEYUP;
        event.key.state=pressed?SDL_PRESSED:SDL_RELEASED; event.key.keysym.scancode=scancode;
        event.key.keysym.sym=SDL_GetKeyFromScancode(scancode);
        passed=(SDL_PushEvent(&event)==1)&&passed;
    };
    key(SDL_SCANCODE_W,true); key(SDL_SCANCODE_D,true);
    IOSPortalCommand keyboard=command();
    check(keyboard.forward>0 && keyboard.side>0,"keyboard WASD movement");
    key(SDL_SCANCODE_W,false); key(SDL_SCANCODE_D,false);
    keyboard=command();
    check(keyboard.forward==0 && keyboard.side==0,"keyboard release");
    const struct {int bit;const char *name;} actions[]={
        {IN_USE,"use"},{IN_JUMP,"jump"},{IN_ATTACK,"attack"},
        {IN_ATTACK2,"attack2"},{IN_DUCK,"duck"}};
    float jumpX=0,jumpY=0;
    for (const auto &action : actions) {
        float x=0,y=0;
        check(findControl(action.name,&x,&y),"loaded profile control lookup");
        if (action.bit==IN_JUMP) {jumpX=x;jumpY=y;}
        send(SDL_FINGERDOWN,42,x,y);
        check((command().buttons&action.bit)!=0,action.name);
        send(SDL_FINGERUP,42,x,y);
        check((command().buttons&action.bit)==0,"action release");
    }
    send(SDL_FINGERDOWN,43,moveX,moveY); command();
    send(SDL_FINGERMOTION,43,moveX,moveY-.04f,0,-.04f);
    send(SDL_FINGERDOWN,44,jumpX,jumpY);
    check(command().forward>0,"held controls before focus loss");
    // Menu visibility must not swallow the release generated by cancellation.
    g_pVGuiPanel->SetVisible(ui,true);
    SDL_Event lost={}; lost.type=SDL_WINDOWEVENT; lost.window.event=SDL_WINDOWEVENT_FOCUS_LOST;
    passed=(SDL_PushEvent(&lost)==1)&&passed;
    IOSPortalCommand cancelled=command();
    check(cancelled.forward==0 && cancelled.side==0 && !(cancelled.buttons&IN_JUMP),"focus cancellation while menu visible");
    send(SDL_FINGERMOTION,43,moveX,moveY-.08f,0,-.04f);
    check(command().forward==0,"motion after cancellation ignored");
    send(SDL_FINGERDOWN,45,jumpX,jumpY);
    check(!(command().buttons&IN_JUMP),"menu suppresses new gameplay presses");
    send(SDL_FINGERUP,45,jumpX,jumpY); command();
    g_pVGuiPanel->SetVisible(ui,visible);
    engineClient->SetViewAngles(originalAngles);
    SDL_FlushEvents(SDL_FINGERDOWN,SDL_FINGERMOTION);
    SDL_Event window; SDL_PeepEvents(&window,1,SDL_GETEVENT,SDL_WINDOWEVENT,SDL_WINDOWEVENT);
    snprintf(detail,capacity,"SDL -> engine dispatcher -> Portal touch -> CUserCmd + codec + controls + focus cancellation: %s",passed?"PASS":"FAIL");
    Msg("%s\n",detail); return passed;
}
